name: Bug Report
description: Report a bug or issue with a component or utility
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below.

  - type: dropdown
    id: component-type
    attributes:
      label: Component Type
      description: Which type of component is affected?
      options:
        - Code Block Component
        - Block (multi-tab, package manager, etc.)
        - Utility (Shiki, Sugar-High)
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: component-name
    attributes:
      label: Component/Utility Name
      description: Name of the specific component or utility
      placeholder: code-block, copy-button, shiki-highlighter
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the bug
      placeholder: The component doesn't render when...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Import the component
        2. Pass props with...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      value: |
        - OS:
        - Browser:
        - Node version:
        - Next.js version:
      render: markdown
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, error messages, or other relevant information
