name: Feature Request
description: Suggest a new component, utility, or feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Component
        - New Block
        - New Utility
        - Component Enhancement
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the feature
      placeholder: I'd like to see a component that...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature be used?
      placeholder: This would be useful for...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Links to similar implementations or mockups
      placeholder: |
        - https://example.com/component
        - [Attach mockup images]

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information about the feature
