import type { Metadata } from "next";
import type { ReactNode } from "react";

// Styles:
import "@/styles/globals.css";
import "@/styles/codeblock.css";
import { container } from "@/ui/container";
import { fontMono, fontSans, fontHeadings } from "@/ui/fonts";
import { cn } from "@/utils/cn";

// Providers:
import { ThemeProvider } from "@/providers/themeProvider";
import Header from "@/components/header";
import Footer from "@/components/footer";

// Metadata:
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// App layout:
export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          `${fontSans.variable} ${fontHeadings.variable} ${fontMono.variable}`,
          "bg-neutral-100 dark:bg-neutral-900",
          "scroll-smooth font-sans antialiased",
          "text-neutral-900 dark:text-neutral-50",
          "selection:bg-neutral-300 dark:selection:bg-neutral-700",
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className={cn(container, "py-10", "flex min-h-dvh flex-col")}>
            <Header />
            <main>{children}</main>
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
