import type { Metadata } from "next";
import type { ReactNode } from "react";

// Styles:
import "@/styles/globals.css";
import { fontMono, fontSans } from "@/ui/fonts";
import { cn } from "@/utils/cn";

// Metadata:
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// App layout:
export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          `${fontSans.variable} ${fontMono.variable}`,
          "bg-neutral-50 dark:bg-neutral-900",
          "font-sans antialiased scroll-smooth",
          "text-neutral-900 dark:text-neutral-50",
        )}
      >
        {children}
      </body>
    </html>
  );
}
