import type { Metadata } from "next";

// Styles:
import "@/styles/globals.css";
import { fontMono, fontSans } from "@/ui/fonts";

// Metadata:
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// App layout:
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} ${fontMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
